// season 데이터
export const generations = [
  { id: 1, season: 1, image: '/placeholder.svg?height=400&width=300' },
  { id: 2, season: 2, image: '/placeholder.svg?height=400&width=300' },
  { id: 3, season: 3, image: '/placeholder.svg?height=400&width=300' },
  { id: 4, season: 4, image: '/placeholder.svg?height=400&width=300' },
  { id: 5, season: 5, image: '/placeholder.svg?height=400&width=300' },
  { id: 6, season: 6, image: '/placeholder.svg?height=400&width=300' },
  { id: 7, season: 7, image: '/placeholder.svg?height=400&width=300' },
  { id: 8, season: 8, image: '/placeholder.svg?height=400&width=300' },
];

// 출연진 데이터
export const cast = [
  {
    name: '영수',
    birth: 1987,
    job: '수의사',
    season: 24,
    돌싱: false,
    gender: '남자',
    child: false,
    result: { 승: 0, 패: 0 },
    win: 0,
    image: '/placeholder.svg?height=400&width=300',
  },
  {
    name: '영호',
    birth: 1988,
    job: '스타트업 앱 개발자',
    season: 24,
    돌싱: false,
    성별: '남자',
    child: false,
    result: { 승: 0, 패: 0 },
    win: 0,
    image: '/placeholder.svg?height=400&width=300',
  },
  {
    name: '영식',
    birth: 1994,
    job: '창원시 8급 토목직 공무원',
    season: 24,
    돌싱: false,
    성별: '남자',
    child: false,
    result: { 승: 0, 패: 0 },
    win: 0,
    image: '/placeholder.svg?height=400&width=300',
  },
  {
    name: '영철',
    birth: 1993,
    job: '유도 선수',
    season: 24,
    돌싱: false,
    성별: '남자',
    child: false,
    result: { 승: 0, 패: 0 },
    win: 0,
    image: '/placeholder.svg?height=400&width=300',
  },
  {
    name: '광수',
    birth: 1993,
    job: '스타트업 업체 COO, 전 새만금개발청 5급 사무관',
    season: 24,
    돌싱: false,
    성별: '남자',
    child: false,
    result: { 승: 0, 패: 0 },
    win: 0,
    image: '/placeholder.svg?height=400&width=300',
  },
  {
    name: '상철',
    birth: 1991,
    job: '수의사',
    season: 24,
    돌싱: false,
    성별: '남자',
    child: false,
    result: { 승: 0, 패: 0 },
    win: 0,
    image: '/placeholder.svg?height=400&width=300',
  },
  {
    name: '영숙',
    birth: 1995,
    job: '서울특별시 교육행정직 7급 공무원',
    season: 24,
    돌싱: false,
    성별: '여자',
    child: false,
    result: { 승: 0, 패: 0 },
    win: 0,
    image: '/placeholder.svg?height=400&width=300',
  },
  {
    name: '정숙',
    birth: 1994,
    job: '개인 사업 준비(전 새마을금고 직원)',
    season: 24,
    돌싱: false,
    성별: '여자',
    child: false,
    result: { 승: 0, 패: 0 },
    win: 0,
    image: '/placeholder.svg?height=400&width=300',
  },
  {
    name: '순자',
    birth: 1993,
    job: '중앙행정기관 행정직 8급 공무원',
    season: 24,
    돌싱: false,
    성별: '여자',
    child: false,
    result: { 승: 0, 패: 0 },
    win: 0,
    image: '/placeholder.svg?height=400&width=300',
  },
  {
    name: '영자',
    birth: 1991,
    job: '영유아 오감 놀이 업체 대표',
    season: 24,
    돌싱: false,
    성별: '여자',
    child: false,
    result: { 승: 0, 패: 0 },
    win: 0,
    image: '/placeholder.svg?height=400&width=300',
  },
  {
    name: '옥순',
    birth: 1989,
    job: 'KT 브랜드 전략실 근무',
    season: 24,
    돌싱: false,
    성별: '여자',
    child: false,
    result: { 승: 0, 패: 0 },
    win: 0,
    image: '/placeholder.svg?height=400&width=300',
  },
  {
    name: '현숙',
    birth: 1991,
    job: '병원 약사',
    season: 24,
    돌싱: false,
    성별: '여자',
    child: false,
    result: { 승: 0, 패: 0 },
    win: 0,
    image: '/placeholder.svg?height=400&width=300',
  },
];
